"""Create entities, aliases, and sanctions tables

Revision ID: 29d9215ebe22
Revises: 
Create Date: 2025-07-15 22:08:47.886747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d9215ebe22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias_name', sa.String(length=500), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliases_alias_name'), 'aliases', ['alias_name'], unique=False)
    op.create_table('sanctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sanctioning_body', sa.String(length=200), nullable=False),
    sa.Column('program', sa.String(length=300), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('sanction_type', sa.String(length=100), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('date_imposed', sa.DateTime(), nullable=True),
    sa.Column('date_expires', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.String(length=500), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_program'), 'sanctions', ['program'], unique=False)
    op.create_index(op.f('ix_sanctions_sanctioning_body'), 'sanctions', ['sanctioning_body'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanctions_sanctioning_body'), table_name='sanctions')
    op.drop_index(op.f('ix_sanctions_program'), table_name='sanctions')
    op.drop_table('sanctions')
    op.drop_index(op.f('ix_aliases_alias_name'), table_name='aliases')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
